// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-1\internal\users\user_repository.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-1\internal\users\user_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        model "github.com/gcarrenho/component-based/option-2/internal/users/model"
        gomock "go.uber.org/mock/gomock"
)

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
        ctrl     *gomock.Controller
        recorder *MockuserRepositoryMockRecorder
        isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
        mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
        mock := &MockuserRepository{ctrl: ctrl}
        mock.recorder = &MockuserRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
        return m.recorder
}

// GetUserByID mocks base method.
func (m *MockuserRepository) GetUserByID(userID string) (model.User, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetUserByID", userID)
        ret0, _ := ret[0].(model.User)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockuserRepositoryMockRecorder) GetUserByID(userID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockuserRepository)(nil).GetUserByID), userID)
}