// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\users\user_component.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\users\user_component.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        model "github.com/gcarrenho/component-based/option-2/internal/users/model"
        gomock "go.uber.org/mock/gomock"
)

// MockUserComponent is a mock of UserComponent interface.
type MockUserComponent struct {
        ctrl     *gomock.Controller
        recorder *MockUserComponentMockRecorder
        isgomock struct{}
}

// MockUserComponentMockRecorder is the mock recorder for MockUserComponent.
type MockUserComponentMockRecorder struct {
        mock *MockUserComponent
}

// NewMockUserComponent creates a new mock instance.
func NewMockUserComponent(ctrl *gomock.Controller) *MockUserComponent {
        mock := &MockUserComponent{ctrl: ctrl}
        mock.recorder = &MockUserComponentMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserComponent) EXPECT() *MockUserComponentMockRecorder {
        return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserComponent) CreateUser(userID string) (model.User, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CreateUser", userID)
        ret0, _ := ret[0].(model.User)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserComponentMockRecorder) CreateUser(userID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserComponent)(nil).CreateUser), userID)
}

// FindUserByID mocks base method.
func (m *MockUserComponent) FindUserByID(userID string) (model.User, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "FindUserByID", userID)
        ret0, _ := ret[0].(model.User)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockUserComponentMockRecorder) FindUserByID(userID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockUserComponent)(nil).FindUserByID), userID)
}