// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\users\user_repository.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\users\user_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        model "github.com/gcarrenho/component-based/option-2/internal/users/model"
        gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
        ctrl     *gomock.Controller
        recorder *MockrepositoryMockRecorder
        isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
        mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
        mock := &Mockrepository{ctrl: ctrl}
        mock.recorder = &MockrepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
        return m.recorder
}

// GetByID mocks base method.
func (m *Mockrepository) GetByID(userID string) (model.User, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetByID", userID)
        ret0, _ := ret[0].(model.User)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockrepositoryMockRecorder) GetByID(userID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*Mockrepository)(nil).GetByID), userID)
}