// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-1\internal\payments\payment_component.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-1\internal\payments\payment_component.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        gomock "go.uber.org/mock/gomock"
)

// MockPaymentComponent is a mock of PaymentComponent interface.
type MockPaymentComponent struct {
        ctrl     *gomock.Controller
        recorder *MockPaymentComponentMockRecorder
        isgomock struct{}
}

// MockPaymentComponentMockRecorder is the mock recorder for MockPaymentComponent.
type MockPaymentComponentMockRecorder struct {
        mock *MockPaymentComponent
}

// NewMockPaymentComponent creates a new mock instance.
func NewMockPaymentComponent(ctrl *gomock.Controller) *MockPaymentComponent {
        mock := &MockPaymentComponent{ctrl: ctrl}
        mock.recorder = &MockPaymentComponentMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentComponent) EXPECT() *MockPaymentComponentMockRecorder {
        return m.recorder
}

// ProcessPayment mocks base method.
func (m *MockPaymentComponent) ProcessPayment(orderID string, amount float64) (string, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "ProcessPayment", orderID, amount)
        ret0, _ := ret[0].(string)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockPaymentComponentMockRecorder) ProcessPayment(orderID, amount any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockPaymentComponent)(nil).ProcessPayment), orderID, amount)
}