// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-1\internal\contracts\user\user_service.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-1\internal\contracts\user\user_service.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        user "github.com/gcarrenho/component-based/option-1/internal/contracts/user"
        gomock "go.uber.org/mock/gomock"
)

// MockPaymentUserService is a mock of PaymentUserService interface.
type MockPaymentUserService struct {
        ctrl     *gomock.Controller
        recorder *MockPaymentUserServiceMockRecorder
        isgomock struct{}
}

// MockPaymentUserServiceMockRecorder is the mock recorder for MockPaymentUserService.
type MockPaymentUserServiceMockRecorder struct {
        mock *MockPaymentUserService
}

// NewMockPaymentUserService creates a new mock instance.
func NewMockPaymentUserService(ctrl *gomock.Controller) *MockPaymentUserService {
        mock := &MockPaymentUserService{ctrl: ctrl}
        mock.recorder = &MockPaymentUserServiceMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentUserService) EXPECT() *MockPaymentUserServiceMockRecorder {
        return m.recorder
}

// IsUserActive mocks base method.
func (m *MockPaymentUserService) IsUserActive(userID string) (user.UserDTO, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "IsUserActive", userID)
        ret0, _ := ret[0].(user.UserDTO)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// IsUserActive indicates an expected call of IsUserActive.
func (mr *MockPaymentUserServiceMockRecorder) IsUserActive(userID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserActive", reflect.TypeOf((*MockPaymentUserService)(nil).IsUserActive), userID)
}