// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\orders\contracts\payment\initiator.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\orders\contracts\payment\initiator.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        gomock "go.uber.org/mock/gomock"
)

// MockPaymentInitiator is a mock of PaymentInitiator interface.
type MockPaymentInitiator struct {
        ctrl     *gomock.Controller
        recorder *MockPaymentInitiatorMockRecorder
        isgomock struct{}
}

// MockPaymentInitiatorMockRecorder is the mock recorder for MockPaymentInitiator.
type MockPaymentInitiatorMockRecorder struct {
        mock *MockPaymentInitiator
}

// NewMockPaymentInitiator creates a new mock instance.
func NewMockPaymentInitiator(ctrl *gomock.Controller) *MockPaymentInitiator {
        mock := &MockPaymentInitiator{ctrl: ctrl}
        mock.recorder = &MockPaymentInitiatorMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentInitiator) EXPECT() *MockPaymentInitiatorMockRecorder {
        return m.recorder
}

// InitPayment mocks base method.
func (m *MockPaymentInitiator) InitPayment(orderID string, amount float64, method string) (string, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "InitPayment", orderID, amount, method)
        ret0, _ := ret[0].(string)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// InitPayment indicates an expected call of InitPayment.
func (mr *MockPaymentInitiatorMockRecorder) InitPayment(orderID, amount, method any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitPayment", reflect.TypeOf((*MockPaymentInitiator)(nil).InitPayment), orderID, amount, method)
}