// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\orders\order_repository.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\orders\order_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        model "github.com/gcarrenho/component-based/option-2/internal/orders/model"
        gomock "go.uber.org/mock/gomock"
)

// MockorderRepository is a mock of orderRepository interface.
type MockorderRepository struct {
        ctrl     *gomock.Controller
        recorder *MockorderRepositoryMockRecorder
        isgomock struct{}
}

// MockorderRepositoryMockRecorder is the mock recorder for MockorderRepository.
type MockorderRepositoryMockRecorder struct {
        mock *MockorderRepository
}

// NewMockorderRepository creates a new mock instance.
func NewMockorderRepository(ctrl *gomock.Controller) *MockorderRepository {
        mock := &MockorderRepository{ctrl: ctrl}
        mock.recorder = &MockorderRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderRepository) EXPECT() *MockorderRepositoryMockRecorder {
        return m.recorder
}

// GetOrderByID mocks base method.
func (m *MockorderRepository) GetOrderByID(paymentID string) (model.Order, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetOrderByID", paymentID)
        ret0, _ := ret[0].(model.Order)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockorderRepositoryMockRecorder) GetOrderByID(paymentID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockorderRepository)(nil).GetOrderByID), paymentID)
}