// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-1\internal\orders\order_component.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-1\internal\orders\order_component.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        model "github.com/gcarrenho/component-based/option-2/internal/orders/model"
        gomock "go.uber.org/mock/gomock"
)

// MockOrderComponent is a mock of OrderComponent interface.
type MockOrderComponent struct {
        ctrl     *gomock.Controller
        recorder *MockOrderComponentMockRecorder
        isgomock struct{}
}

// MockOrderComponentMockRecorder is the mock recorder for MockOrderComponent.
type MockOrderComponentMockRecorder struct {
        mock *MockOrderComponent
}

// NewMockOrderComponent creates a new mock instance.
func NewMockOrderComponent(ctrl *gomock.Controller) *MockOrderComponent {
        mock := &MockOrderComponent{ctrl: ctrl}
        mock.recorder = &MockOrderComponentMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderComponent) EXPECT() *MockOrderComponentMockRecorder {
        return m.recorder
}

// FindOrderByID mocks base method.
func (m *MockOrderComponent) FindOrderByID(orderID string) (model.Order, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "FindOrderByID", orderID)
        ret0, _ := ret[0].(model.Order)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// FindOrderByID indicates an expected call of FindOrderByID.
func (mr *MockOrderComponentMockRecorder) FindOrderByID(orderID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrderByID", reflect.TypeOf((*MockOrderComponent)(nil).FindOrderByID), orderID)
}