// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\orders\contracts\payment\payment_status_checker.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\orders\contracts\payment\payment_status_checker.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        gomock "go.uber.org/mock/gomock"
)

// MockPaymentStatusChecker is a mock of PaymentStatusChecker interface.
type MockPaymentStatusChecker struct {
        ctrl     *gomock.Controller
        recorder *MockPaymentStatusCheckerMockRecorder
        isgomock struct{}
}

// MockPaymentStatusCheckerMockRecorder is the mock recorder for MockPaymentStatusChecker.
type MockPaymentStatusCheckerMockRecorder struct {
        mock *MockPaymentStatusChecker
}

// NewMockPaymentStatusChecker creates a new mock instance.
func NewMockPaymentStatusChecker(ctrl *gomock.Controller) *MockPaymentStatusChecker {
        mock := &MockPaymentStatusChecker{ctrl: ctrl}
        mock.recorder = &MockPaymentStatusCheckerMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentStatusChecker) EXPECT() *MockPaymentStatusCheckerMockRecorder {
        return m.recorder
}

// IsPaymentMethodValid mocks base method.
func (m *MockPaymentStatusChecker) IsPaymentMethodValid(method string) bool {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "IsPaymentMethodValid", method)
        ret0, _ := ret[0].(bool)
        return ret0
}

// IsPaymentMethodValid indicates an expected call of IsPaymentMethodValid.
func (mr *MockPaymentStatusCheckerMockRecorder) IsPaymentMethodValid(method any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPaymentMethodValid", reflect.TypeOf((*MockPaymentStatusChecker)(nil).IsPaymentMethodValid), method)
}