// Code generated by MockGen. DO NOT EDIT.
// Source: payment.go
//
// Generated by this command:
//
//	mockgen -source payment.go -destination mocks_test.go -package payment
//

// Package payment is a generated GoMock package.
package payment

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockidempotencyStore is a mock of idempotencyStore interface.
type MockidempotencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockidempotencyStoreMockRecorder
}

// MockidempotencyStoreMockRecorder is the mock recorder for MockidempotencyStore.
type MockidempotencyStoreMockRecorder struct {
	mock *MockidempotencyStore
}

// NewMockidempotencyStore creates a new mock instance.
func NewMockidempotencyStore(ctrl *gomock.Controller) *MockidempotencyStore {
	mock := &MockidempotencyStore{ctrl: ctrl}
	mock.recorder = &MockidempotencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockidempotencyStore) EXPECT() *MockidempotencyStoreMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockidempotencyStore) Acquire(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockidempotencyStoreMockRecorder) Acquire(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockidempotencyStore)(nil).Acquire), ctx, key)
}

// Complete mocks base method.
func (m *MockidempotencyStore) Complete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockidempotencyStoreMockRecorder) Complete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockidempotencyStore)(nil).Complete), ctx, key)
}

// IsCompleted mocks base method.
func (m *MockidempotencyStore) IsCompleted(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCompleted", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCompleted indicates an expected call of IsCompleted.
func (mr *MockidempotencyStoreMockRecorder) IsCompleted(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCompleted", reflect.TypeOf((*MockidempotencyStore)(nil).IsCompleted), ctx, key)
}

// Release mocks base method.
func (m *MockidempotencyStore) Release(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockidempotencyStoreMockRecorder) Release(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockidempotencyStore)(nil).Release), ctx, key)
}

// MockaccountRepository is a mock of accountRepository interface.
type MockaccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockaccountRepositoryMockRecorder
}

// MockaccountRepositoryMockRecorder is the mock recorder for MockaccountRepository.
type MockaccountRepositoryMockRecorder struct {
	mock *MockaccountRepository
}

// NewMockaccountRepository creates a new mock instance.
func NewMockaccountRepository(ctrl *gomock.Controller) *MockaccountRepository {
	mock := &MockaccountRepository{ctrl: ctrl}
	mock.recorder = &MockaccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountRepository) EXPECT() *MockaccountRepositoryMockRecorder {
	return m.recorder
}

// GetAccount mocks base method.
func (m *MockaccountRepository) GetAccount(ctx context.Context, accountID string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, accountID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockaccountRepositoryMockRecorder) GetAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockaccountRepository)(nil).GetAccount), ctx, accountID)
}

// UpdateAccount mocks base method.
func (m *MockaccountRepository) UpdateAccount(ctx context.Context, accountID string, newBalanceCents, expectedVersion int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, accountID, newBalanceCents, expectedVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockaccountRepositoryMockRecorder) UpdateAccount(ctx, accountID, newBalanceCents, expectedVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockaccountRepository)(nil).UpdateAccount), ctx, accountID, newBalanceCents, expectedVersion)
}

// MockreservationStore is a mock of reservationStore interface.
type MockreservationStore struct {
	ctrl     *gomock.Controller
	recorder *MockreservationStoreMockRecorder
}

// MockreservationStoreMockRecorder is the mock recorder for MockreservationStore.
type MockreservationStoreMockRecorder struct {
	mock *MockreservationStore
}

// NewMockreservationStore creates a new mock instance.
func NewMockreservationStore(ctrl *gomock.Controller) *MockreservationStore {
	mock := &MockreservationStore{ctrl: ctrl}
	mock.recorder = &MockreservationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreservationStore) EXPECT() *MockreservationStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockreservationStore) Create(ctx context.Context, id, accountID string, amountCents int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, id, accountID, amountCents)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockreservationStoreMockRecorder) Create(ctx, id, accountID, amountCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockreservationStore)(nil).Create), ctx, id, accountID, amountCents)
}

// Get mocks base method.
func (m *MockreservationStore) Get(ctx context.Context, id string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockreservationStoreMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockreservationStore)(nil).Get), ctx, id)
}

// MockChargeService is a mock of ChargeService interface.
type MockChargeService struct {
	ctrl     *gomock.Controller
	recorder *MockChargeServiceMockRecorder
}

// MockChargeServiceMockRecorder is the mock recorder for MockChargeService.
type MockChargeServiceMockRecorder struct {
	mock *MockChargeService
}

// NewMockChargeService creates a new mock instance.
func NewMockChargeService(ctrl *gomock.Controller) *MockChargeService {
	mock := &MockChargeService{ctrl: ctrl}
	mock.recorder = &MockChargeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChargeService) EXPECT() *MockChargeServiceMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockChargeService) Charge(ctx context.Context, idempotencyKey, accountID string, amountCents int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, idempotencyKey, accountID, amountCents)
	ret0, _ := ret[0].(error)
	return ret0
}

// Charge indicates an expected call of Charge.
func (mr *MockChargeServiceMockRecorder) Charge(ctx, idempotencyKey, accountID, amountCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockChargeService)(nil).Charge), ctx, idempotencyKey, accountID, amountCents)
}

// Refund mocks base method.
func (m *MockChargeService) Refund(ctx context.Context, idempotencyKey, accountID string, amountCents int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refund", ctx, idempotencyKey, accountID, amountCents)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refund indicates an expected call of Refund.
func (mr *MockChargeServiceMockRecorder) Refund(ctx, idempotencyKey, accountID, amountCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockChargeService)(nil).Refund), ctx, idempotencyKey, accountID, amountCents)
}

// Reserve mocks base method.
func (m *MockChargeService) Reserve(ctx context.Context, idempotencyKey, accountID string, amountCents int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, idempotencyKey, accountID, amountCents)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reserve indicates an expected call of Reserve.
func (mr *MockChargeServiceMockRecorder) Reserve(ctx, idempotencyKey, accountID, amountCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockChargeService)(nil).Reserve), ctx, idempotencyKey, accountID, amountCents)
}
