// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mocks_test.go -package fraud
//

// Package fraud is a generated GoMock package.
package fraud

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockpaymentGateway is a mock of paymentGateway interface.
type MockpaymentGateway struct {
	ctrl     *gomock.Controller
	recorder *MockpaymentGatewayMockRecorder
}

// MockpaymentGatewayMockRecorder is the mock recorder for MockpaymentGateway.
type MockpaymentGatewayMockRecorder struct {
	mock *MockpaymentGateway
}

// NewMockpaymentGateway creates a new mock instance.
func NewMockpaymentGateway(ctrl *gomock.Controller) *MockpaymentGateway {
	mock := &MockpaymentGateway{ctrl: ctrl}
	mock.recorder = &MockpaymentGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpaymentGateway) EXPECT() *MockpaymentGatewayMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockpaymentGateway) Charge(ctx context.Context, key, accountID string, amountCents int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, key, accountID, amountCents)
	ret0, _ := ret[0].(error)
	return ret0
}

// Charge indicates an expected call of Charge.
func (mr *MockpaymentGatewayMockRecorder) Charge(ctx, key, accountID, amountCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockpaymentGateway)(nil).Charge), ctx, key, accountID, amountCents)
}

// Reserve mocks base method.
func (m *MockpaymentGateway) Reserve(ctx context.Context, key, accountID string, amountCents int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, key, accountID, amountCents)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reserve indicates an expected call of Reserve.
func (mr *MockpaymentGatewayMockRecorder) Reserve(ctx, key, accountID, amountCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockpaymentGateway)(nil).Reserve), ctx, key, accountID, amountCents)
}
