// Code generated by MockGen. DO NOT EDIT.
// Source: engine.go
//
// Generated by this command:
//
//	mockgen -source engine.go -destination mocks_test.go -package banking
//

// Package banking is a generated GoMock package.
package banking

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRail is a mock of Rail interface.
type MockRail struct {
	ctrl     *gomock.Controller
	recorder *MockRailMockRecorder
	isgomock struct{}
}

// MockRailMockRecorder is the mock recorder for MockRail.
type MockRailMockRecorder struct {
	mock *MockRail
}

// NewMockRail creates a new mock instance.
func NewMockRail(ctrl *gomock.Controller) *MockRail {
	mock := &MockRail{ctrl: ctrl}
	mock.recorder = &MockRailMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRail) EXPECT() *MockRailMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockRail) Send(ctx context.Context, order PaymentOrder) (PaymentOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, order)
	ret0, _ := ret[0].(PaymentOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockRailMockRecorder) Send(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockRail)(nil).Send), ctx, order)
}

// MockLedger is a mock of Ledger interface.
type MockLedger struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerMockRecorder
	isgomock struct{}
}

// MockLedgerMockRecorder is the mock recorder for MockLedger.
type MockLedgerMockRecorder struct {
	mock *MockLedger
}

// NewMockLedger creates a new mock instance.
func NewMockLedger(ctrl *gomock.Controller) *MockLedger {
	mock := &MockLedger{ctrl: ctrl}
	mock.recorder = &MockLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedger) EXPECT() *MockLedgerMockRecorder {
	return m.recorder
}

// Debit mocks base method.
func (m *MockLedger) Debit(ctx context.Context, orderID, iban string, amountCents, expectedVersion int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Debit", ctx, orderID, iban, amountCents, expectedVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// Debit indicates an expected call of Debit.
func (mr *MockLedgerMockRecorder) Debit(ctx, orderID, iban, amountCents, expectedVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debit", reflect.TypeOf((*MockLedger)(nil).Debit), ctx, orderID, iban, amountCents, expectedVersion)
}

// GetBalance mocks base method.
func (m *MockLedger) GetBalance(ctx context.Context, iban string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, iban)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockLedgerMockRecorder) GetBalance(ctx, iban any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockLedger)(nil).GetBalance), ctx, iban)
}

// Reverse mocks base method.
func (m *MockLedger) Reverse(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reverse", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reverse indicates an expected call of Reverse.
func (mr *MockLedgerMockRecorder) Reverse(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reverse", reflect.TypeOf((*MockLedger)(nil).Reverse), ctx, orderID)
}

// Settle mocks base method.
func (m *MockLedger) Settle(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settle", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Settle indicates an expected call of Settle.
func (mr *MockLedgerMockRecorder) Settle(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settle", reflect.TypeOf((*MockLedger)(nil).Settle), ctx, orderID)
}

// MockPaymentEngine is a mock of PaymentEngine interface.
type MockPaymentEngine struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentEngineMockRecorder
	isgomock struct{}
}

// MockPaymentEngineMockRecorder is the mock recorder for MockPaymentEngine.
type MockPaymentEngineMockRecorder struct {
	mock *MockPaymentEngine
}

// NewMockPaymentEngine creates a new mock instance.
func NewMockPaymentEngine(ctrl *gomock.Controller) *MockPaymentEngine {
	mock := &MockPaymentEngine{ctrl: ctrl}
	mock.recorder = &MockPaymentEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentEngine) EXPECT() *MockPaymentEngineMockRecorder {
	return m.recorder
}

// Initiate mocks base method.
func (m *MockPaymentEngine) Initiate(ctx context.Context, order PaymentOrder) (PaymentOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initiate", ctx, order)
	ret0, _ := ret[0].(PaymentOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initiate indicates an expected call of Initiate.
func (mr *MockPaymentEngineMockRecorder) Initiate(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initiate", reflect.TypeOf((*MockPaymentEngine)(nil).Initiate), ctx, order)
}
