// Code generated by MockGen. DO NOT EDIT.
// Source: authorization.go
//
// Generated by this command:
//
//	mockgen -source authorization.go -destination mocks_test.go -package authorization
//

// Package authorization is a generated GoMock package.
package authorization

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mocknetwork is a mock of network interface.
type Mocknetwork struct {
	ctrl     *gomock.Controller
	recorder *MocknetworkMockRecorder
}

// MocknetworkMockRecorder is the mock recorder for Mocknetwork.
type MocknetworkMockRecorder struct {
	mock *Mocknetwork
}

// NewMocknetwork creates a new mock instance.
func NewMocknetwork(ctrl *gomock.Controller) *Mocknetwork {
	mock := &Mocknetwork{ctrl: ctrl}
	mock.recorder = &MocknetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocknetwork) EXPECT() *MocknetworkMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *Mocknetwork) Authorize(ctx context.Context, txn CardTransaction) (CardTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, txn)
	ret0, _ := ret[0].(CardTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MocknetworkMockRecorder) Authorize(ctx, txn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*Mocknetwork)(nil).Authorize), ctx, txn)
}

// MockidempotencyStore is a mock of idempotencyStore interface.
type MockidempotencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockidempotencyStoreMockRecorder
}

// MockidempotencyStoreMockRecorder is the mock recorder for MockidempotencyStore.
type MockidempotencyStoreMockRecorder struct {
	mock *MockidempotencyStore
}

// NewMockidempotencyStore creates a new mock instance.
func NewMockidempotencyStore(ctrl *gomock.Controller) *MockidempotencyStore {
	mock := &MockidempotencyStore{ctrl: ctrl}
	mock.recorder = &MockidempotencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockidempotencyStore) EXPECT() *MockidempotencyStoreMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockidempotencyStore) Acquire(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockidempotencyStoreMockRecorder) Acquire(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockidempotencyStore)(nil).Acquire), ctx, key)
}

// Complete mocks base method.
func (m *MockidempotencyStore) Complete(ctx context.Context, key, authCode, networkRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, key, authCode, networkRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockidempotencyStoreMockRecorder) Complete(ctx, key, authCode, networkRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockidempotencyStore)(nil).Complete), ctx, key, authCode, networkRef)
}

// GetCompleted mocks base method.
func (m *MockidempotencyStore) GetCompleted(ctx context.Context, key string) (string, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompleted", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetCompleted indicates an expected call of GetCompleted.
func (mr *MockidempotencyStoreMockRecorder) GetCompleted(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompleted", reflect.TypeOf((*MockidempotencyStore)(nil).GetCompleted), ctx, key)
}

// Release mocks base method.
func (m *MockidempotencyStore) Release(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockidempotencyStoreMockRecorder) Release(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockidempotencyStore)(nil).Release), ctx, key)
}

// MockAuthorizer is a mock of Authorizer interface.
type MockAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerMockRecorder
}

// MockAuthorizerMockRecorder is the mock recorder for MockAuthorizer.
type MockAuthorizerMockRecorder struct {
	mock *MockAuthorizer
}

// NewMockAuthorizer creates a new mock instance.
func NewMockAuthorizer(ctrl *gomock.Controller) *MockAuthorizer {
	mock := &MockAuthorizer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizer) EXPECT() *MockAuthorizerMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockAuthorizer) Authorize(ctx context.Context, txn CardTransaction) (CardTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, txn)
	ret0, _ := ret[0].(CardTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockAuthorizerMockRecorder) Authorize(ctx, txn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockAuthorizer)(nil).Authorize), ctx, txn)
}
