// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// To regenerate: sqlc generate -f sqlc.yaml

package ledger

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX is satisfied by *pgxpool.Pool and pgx.Tx — allows Queries to run inside
// or outside a transaction without changing the method signatures.
type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

// WithTx returns a new Queries scoped to tx so multi-step operations are atomic.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}
