// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// To regenerate: sqlc generate -f sqlc.yaml

package ledger

import "time"

type Account struct {
	Iban         string
	BalanceCents int64
	Version      int64
}

type PaymentDebit struct {
	OrderID     string
	Iban        string
	AmountCents int64
	Status      string
	CreatedAt   time.Time
}
