// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql
// To regenerate: sqlc generate -f sqlc.yaml

package ledger

import "context"

// ── accounts ──────────────────────────────────────────────────────────────────

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts (iban, balance_cents, version)
VALUES ($1, 1000000, 0) ON CONFLICT DO NOTHING`

func (q *Queries) UpsertAccount(ctx context.Context, iban string) error {
	_, err := q.db.Exec(ctx, upsertAccount, iban)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT balance_cents, version FROM accounts WHERE iban = $1`

type GetAccountRow struct {
	BalanceCents int64
	Version      int64
}

func (q *Queries) GetAccount(ctx context.Context, iban string) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, iban)
	var i GetAccountRow
	err := row.Scan(&i.BalanceCents, &i.Version)
	return i, err
}

// DebitAccountParams maps to the three $N parameters of the OCC UPDATE.
// BalanceCents is the amount to debit — named after the column sqlc infers from context.
type DebitAccountParams struct {
	BalanceCents    int64  // amount to debit ($1)
	Iban            string // $2
	ExpectedVersion int64  // $3
}

const debitAccount = `-- name: DebitAccount :execrows
UPDATE accounts
SET balance_cents = balance_cents - $1,
    version       = version + 1
WHERE iban = $2
  AND version = $3
  AND balance_cents >= $1`

// DebitAccount returns the number of rows affected (1 = success, 0 = version conflict or insufficient funds).
func (q *Queries) DebitAccount(ctx context.Context, arg DebitAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, debitAccount, arg.BalanceCents, arg.Iban, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountForConflict = `-- name: GetAccountForConflict :one
SELECT version, balance_cents FROM accounts WHERE iban = $1`

type GetAccountForConflictRow struct {
	Version      int64
	BalanceCents int64
}

func (q *Queries) GetAccountForConflict(ctx context.Context, iban string) (GetAccountForConflictRow, error) {
	row := q.db.QueryRow(ctx, getAccountForConflict, iban)
	var i GetAccountForConflictRow
	err := row.Scan(&i.Version, &i.BalanceCents)
	return i, err
}

type RestoreBalanceParams struct {
	AmountCents int64
	Iban        string
}

const restoreBalance = `-- name: RestoreBalance :exec
UPDATE accounts
SET balance_cents = balance_cents + $1,
    version       = version + 1
WHERE iban = $2`

func (q *Queries) RestoreBalance(ctx context.Context, arg RestoreBalanceParams) error {
	_, err := q.db.Exec(ctx, restoreBalance, arg.AmountCents, arg.Iban)
	return err
}

// ── payment_debits ────────────────────────────────────────────────────────────

type InsertDebitParams struct {
	OrderID     string
	Iban        string
	AmountCents int64
}

const insertDebit = `-- name: InsertDebit :exec
INSERT INTO payment_debits (order_id, iban, amount_cents, status)
VALUES ($1, $2, $3, 'PENDING')`

func (q *Queries) InsertDebit(ctx context.Context, arg InsertDebitParams) error {
	_, err := q.db.Exec(ctx, insertDebit, arg.OrderID, arg.Iban, arg.AmountCents)
	return err
}

const settleDebit = `-- name: SettleDebit :exec
UPDATE payment_debits
SET status = 'SETTLED'
WHERE order_id = $1
  AND status   = 'PENDING'`

func (q *Queries) SettleDebit(ctx context.Context, orderID string) error {
	_, err := q.db.Exec(ctx, settleDebit, orderID)
	return err
}

type ReverseDebitRow struct {
	Iban        string
	AmountCents int64
}

const reverseDebit = `-- name: ReverseDebit :one
UPDATE payment_debits
SET status = 'REVERSED'
WHERE order_id = $1
  AND status   = 'PENDING'
RETURNING iban, amount_cents`

func (q *Queries) ReverseDebit(ctx context.Context, orderID string) (ReverseDebitRow, error) {
	row := q.db.QueryRow(ctx, reverseDebit, orderID)
	var i ReverseDebitRow
	err := row.Scan(&i.Iban, &i.AmountCents)
	return i, err
}
