// Package ledger is the PostgreSQL-backed Ledger adapter for payment-worker.
// SQL is owned by query.sql; query.sql.go is generated by sqlc.
// To regenerate after changing query.sql: sqlc generate -f sqlc.yaml
//
//go:generate sqlc generate -f sqlc.yaml
package ledger

import (
	"context"
	"embed"
	"errors"
	"fmt"
	"net/url"

	migrate "github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database/pgx/v5" // registers "pgx5" driver
	"github.com/golang-migrate/migrate/v4/source/iofs"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	banking "github.com/examples/banking-core"
)

//go:embed migrations/*.sql
var migrationFS embed.FS

// Store implements banking.Ledger. It wraps the sqlc-generated Queries and
// adds the transaction orchestration that spans multiple generated calls.
type Store struct {
	db *pgxpool.Pool
	q  *Queries
}

// NewStore applies pending migrations then opens the connection pool.
func NewStore(connString string) (*Store, error) {
	if err := runMigrations(connString); err != nil {
		return nil, err
	}
	pool, err := pgxpool.New(context.Background(), connString)
	if err != nil {
		return nil, fmt.Errorf("ledger: connect: %w", err)
	}
	if err := pool.Ping(context.Background()); err != nil {
		return nil, fmt.Errorf("ledger: ping: %w", err)
	}
	return &Store{db: pool, q: New(pool)}, nil
}

// runMigrations applies all pending *.up.sql files via golang-migrate.
// ErrNoChange is not an error — it means the schema is already up to date.
func runMigrations(connString string) error {
	src, err := iofs.New(migrationFS, "migrations")
	if err != nil {
		return fmt.Errorf("ledger: migration source: %w", err)
	}
	// golang-migrate's pgx/v5 driver requires the "pgx5" URL scheme.
	u, err := url.Parse(connString)
	if err != nil {
		return fmt.Errorf("ledger: parse url: %w", err)
	}
	u.Scheme = "pgx5"
	m, err := migrate.NewWithSourceInstance("iofs", src, u.String())
	if err != nil {
		return fmt.Errorf("ledger: migration init: %w", err)
	}
	defer m.Close()
	if err := m.Up(); err != nil && !errors.Is(err, migrate.ErrNoChange) {
		return fmt.Errorf("ledger: migrate up: %w", err)
	}
	return nil
}

func (s *Store) Close() { s.db.Close() }

// GetBalance auto-creates the account on first access (demo convenience).
func (s *Store) GetBalance(ctx context.Context, iban string) (int64, int64, error) {
	if err := s.q.UpsertAccount(ctx, iban); err != nil {
		return 0, 0, fmt.Errorf("ledger: upsert account: %w", err)
	}
	row, err := s.q.GetAccount(ctx, iban)
	if err != nil {
		return 0, 0, fmt.Errorf("ledger: get balance: %w", err)
	}
	return row.BalanceCents, row.Version, nil
}

// Debit applies an OCC-guarded debit inside a single transaction.
// Creates a payment_debits journal entry keyed by orderID for Settle/Reverse.
func (s *Store) Debit(ctx context.Context, orderID, iban string, amountCents, expectedVersion int64) error {
	tx, err := s.db.Begin(ctx)
	if err != nil {
		return fmt.Errorf("ledger: debit begin: %w", err)
	}
	defer tx.Rollback(ctx)

	qtx := s.q.WithTx(tx)

	rows, err := qtx.DebitAccount(ctx, DebitAccountParams{
		BalanceCents:    amountCents,
		Iban:            iban,
		ExpectedVersion: expectedVersion,
	})
	if err != nil {
		return fmt.Errorf("ledger: debit update: %w", err)
	}
	if rows == 0 {
		// Distinguish version conflict from insufficient funds.
		conflict, err := qtx.GetAccountForConflict(ctx, iban)
		if err != nil {
			return fmt.Errorf("ledger: debit read: %w", err)
		}
		if conflict.Version != expectedVersion {
			return banking.ErrVersionConflict
		}
		return banking.ErrInsufficientBalance
	}
	if err := qtx.InsertDebit(ctx, InsertDebitParams{
		OrderID:     orderID,
		Iban:        iban,
		AmountCents: amountCents,
	}); err != nil {
		return fmt.Errorf("ledger: insert debit: %w", err)
	}
	return tx.Commit(ctx)
}

// Settle marks the journal entry SETTLED after the rail confirms the transfer.
func (s *Store) Settle(ctx context.Context, orderID string) error {
	if err := s.q.SettleDebit(ctx, orderID); err != nil {
		return fmt.Errorf("ledger: settle: %w", err)
	}
	return nil
}

// Reverse cancels a pending debit and restores the debtor's balance atomically.
func (s *Store) Reverse(ctx context.Context, orderID string) error {
	tx, err := s.db.Begin(ctx)
	if err != nil {
		return fmt.Errorf("ledger: reverse begin: %w", err)
	}
	defer tx.Rollback(ctx)

	qtx := s.q.WithTx(tx)

	debit, err := qtx.ReverseDebit(ctx, orderID)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil // already settled or reversed — safe no-op
	}
	if err != nil {
		return fmt.Errorf("ledger: reverse debit: %w", err)
	}
	if err := qtx.RestoreBalance(ctx, RestoreBalanceParams{
		AmountCents: debit.AmountCents,
		Iban:        debit.Iban,
	}); err != nil {
		return fmt.Errorf("ledger: restore balance: %w", err)
	}
	return tx.Commit(ctx)
}
