// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\payments\payment_repository.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\payments\payment_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	"github.com/gcarrenho/component-based/option-2/internal/payments/model"
	gomock "go.uber.org/mock/gomock"
)

// MockpaymentRepository is a mock of paymentRepository interface.
type MockpaymentRepository struct {
        ctrl     *gomock.Controller
        recorder *MockpaymentRepositoryMockRecorder
        isgomock struct{}
}

// MockpaymentRepositoryMockRecorder is the mock recorder for MockpaymentRepository.
type MockpaymentRepositoryMockRecorder struct {
        mock *MockpaymentRepository
}

// NewMockpaymentRepository creates a new mock instance.
func NewMockpaymentRepository(ctrl *gomock.Controller) *MockpaymentRepository {
        mock := &MockpaymentRepository{ctrl: ctrl}
        mock.recorder = &MockpaymentRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpaymentRepository) EXPECT() *MockpaymentRepositoryMockRecorder {
        return m.recorder
}

// GetPaymentByID mocks base method.
func (m *MockpaymentRepository) GetPaymentByID(paymentID string) (model.Payment, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetPaymentByID", paymentID)
        ret0, _ := ret[0].(model.Payment)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetPaymentByID indicates an expected call of GetPaymentByID.
func (mr *MockpaymentRepositoryMockRecorder) GetPaymentByID(paymentID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByID", reflect.TypeOf((*MockpaymentRepository)(nil).GetPaymentByID), paymentID)
}