// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\payments\contracts\order\updater.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\4-component-based\option-2\internal\payments\contracts\order\updater.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        gomock "go.uber.org/mock/gomock"
)

// MockOrderUpdater is a mock of OrderUpdater interface.
type MockOrderUpdater struct {
        ctrl     *gomock.Controller
        recorder *MockOrderUpdaterMockRecorder
        isgomock struct{}
}

// MockOrderUpdaterMockRecorder is the mock recorder for MockOrderUpdater.
type MockOrderUpdaterMockRecorder struct {
        mock *MockOrderUpdater
}

// NewMockOrderUpdater creates a new mock instance.
func NewMockOrderUpdater(ctrl *gomock.Controller) *MockOrderUpdater {
        mock := &MockOrderUpdater{ctrl: ctrl}
        mock.recorder = &MockOrderUpdaterMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderUpdater) EXPECT() *MockOrderUpdaterMockRecorder {
        return m.recorder
}

// MarkOrderAsPaid mocks base method.
func (m *MockOrderUpdater) MarkOrderAsPaid(orderID, paymentID string) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "MarkOrderAsPaid", orderID, paymentID)
        ret0, _ := ret[0].(error)
        return ret0
}

// MarkOrderAsPaid indicates an expected call of MarkOrderAsPaid.
func (mr *MockOrderUpdaterMockRecorder) MarkOrderAsPaid(orderID, paymentID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOrderAsPaid", reflect.TypeOf((*MockOrderUpdater)(nil).MarkOrderAsPaid), orderID, paymentID)
}