// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import domains "github.com/gcarrenho/hackernews/internal/core/domains"

type Link struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
	User    *User  `json:"user"`
}

type Mutation struct {
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (l *Link) LinkToDomain() domains.Link{
	return domains.Link{
		ID:      l.ID,
		Address: l.Address,
		Title:   l.Title,
		User: &domains.User{
			ID:       l.User.ID,
			Username: l.User.Name,
		},
	}
}

func DomainToLink(link domains.Link) Link{
	return Link{
		ID:      link.ID,
		Address: link.Address,
		Title:   link.Title,
		User: &User{
			ID:   link.User.ID,
			Name: link.User.Username,
		},
	}
}