// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\3-hexagonal\good-example\internal\orders\core\ports\orders_repository.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\3-hexagonal\good-example\internal\orders\core\ports\orders_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        model "github.com/gcarrenho/hexagonal/good-example/internal/orders/core/model"
        gomock "go.uber.org/mock/gomock"
)

// MockOrdersRepository is a mock of OrdersRepository interface.
type MockOrdersRepository struct {
        ctrl     *gomock.Controller
        recorder *MockOrdersRepositoryMockRecorder
        isgomock struct{}
}

// MockOrdersRepositoryMockRecorder is the mock recorder for MockOrdersRepository.
type MockOrdersRepositoryMockRecorder struct {
        mock *MockOrdersRepository
}

// NewMockOrdersRepository creates a new mock instance.
func NewMockOrdersRepository(ctrl *gomock.Controller) *MockOrdersRepository {
        mock := &MockOrdersRepository{ctrl: ctrl}
        mock.recorder = &MockOrdersRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersRepository) EXPECT() *MockOrdersRepositoryMockRecorder {
        return m.recorder
}

// GetOrderByID mocks base method.
func (m *MockOrdersRepository) GetOrderByID(orderID string) (model.Order, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetOrderByID", orderID)
        ret0, _ := ret[0].(model.Order)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrdersRepositoryMockRecorder) GetOrderByID(orderID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrdersRepository)(nil).GetOrderByID), orderID)
}