// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\3-hexagonal\good-example\internal\orders\core\ports\payment_port.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\3-hexagonal\good-example\internal\orders\core\ports\payment_port.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        context "context"
        reflect "reflect"

        ports "github.com/gcarrenho/hexagonal/good-example/internal/orders/core/ports"
        gomock "go.uber.org/mock/gomock"
)

// MockOrderPaymentChecker is a mock of OrderPaymentChecker interface.
type MockOrderPaymentChecker struct {
        ctrl     *gomock.Controller
        recorder *MockOrderPaymentCheckerMockRecorder
        isgomock struct{}
}

// MockOrderPaymentCheckerMockRecorder is the mock recorder for MockOrderPaymentChecker.
type MockOrderPaymentCheckerMockRecorder struct {
        mock *MockOrderPaymentChecker
}

// NewMockOrderPaymentChecker creates a new mock instance.
func NewMockOrderPaymentChecker(ctrl *gomock.Controller) *MockOrderPaymentChecker {
        mock := &MockOrderPaymentChecker{ctrl: ctrl}
        mock.recorder = &MockOrderPaymentCheckerMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderPaymentChecker) EXPECT() *MockOrderPaymentCheckerMockRecorder {
        return m.recorder
}

// OrderPaymentStatus mocks base method.
func (m *MockOrderPaymentChecker) OrderPaymentStatus(ctx context.Context, orderID string) (ports.PaymentDTO, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "OrderPaymentStatus", ctx, orderID)
        ret0, _ := ret[0].(ports.PaymentDTO)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// OrderPaymentStatus indicates an expected call of OrderPaymentStatus.
func (mr *MockOrderPaymentCheckerMockRecorder) OrderPaymentStatus(ctx, orderID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderPaymentStatus", reflect.TypeOf((*MockOrderPaymentChecker)(nil).OrderPaymentStatus), ctx, orderID)
}