// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\3-hexagonal\good-example\internal\payments\core\ports\payments_repository.go
//
// Generated by this command:
//
//      mockgen -source=C:\Users\CarrenoG\go-workspace\src\examples\clean-architecture\3-hexagonal\good-example\internal\payments\core\ports\payments_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        context "context"
        reflect "reflect"

        model "github.com/gcarrenho/hexagonal/good-example/internal/payments/core/model"
        gomock "go.uber.org/mock/gomock"
)

// MockPaymentsRepository is a mock of PaymentsRepository interface.
type MockPaymentsRepository struct {
        ctrl     *gomock.Controller
        recorder *MockPaymentsRepositoryMockRecorder
        isgomock struct{}
}

// MockPaymentsRepositoryMockRecorder is the mock recorder for MockPaymentsRepository.
type MockPaymentsRepositoryMockRecorder struct {
        mock *MockPaymentsRepository
}

// NewMockPaymentsRepository creates a new mock instance.
func NewMockPaymentsRepository(ctrl *gomock.Controller) *MockPaymentsRepository {
        mock := &MockPaymentsRepository{ctrl: ctrl}
        mock.recorder = &MockPaymentsRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentsRepository) EXPECT() *MockPaymentsRepositoryMockRecorder {
        return m.recorder
}

// GetPaymentByID mocks base method.
func (m *MockPaymentsRepository) GetPaymentByID(ctx context.Context, paymentID string) (model.Payment, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetPaymentByID", ctx, paymentID)
        ret0, _ := ret[0].(model.Payment)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetPaymentByID indicates an expected call of GetPaymentByID.
func (mr *MockPaymentsRepositoryMockRecorder) GetPaymentByID(ctx, paymentID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByID", reflect.TypeOf((*MockPaymentsRepository)(nil).GetPaymentByID), ctx, paymentID)
}