// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/CarrenoG/go-workspace/src/examples/clean-architecture/3-hexagonal/bad-example/internal/core/ports/orders_service.go
//
// Generated by this command:
//
//      mockgen -source=C:/Users/CarrenoG/go-workspace/src/examples/clean-architecture/3-hexagonal/bad-example/internal/core/ports/orders_service.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        model "github.com/gcarrenho/hexagonal/bad-example/internal/core/model"
        gomock "go.uber.org/mock/gomock"
)

// MockOrdersService is a mock of OrdersService interface.
type MockOrdersService struct {
        ctrl     *gomock.Controller
        recorder *MockOrdersServiceMockRecorder
        isgomock struct{}
}

// MockOrdersServiceMockRecorder is the mock recorder for MockOrdersService.
type MockOrdersServiceMockRecorder struct {
        mock *MockOrdersService
}

// NewMockOrdersService creates a new mock instance.
func NewMockOrdersService(ctrl *gomock.Controller) *MockOrdersService {
        mock := &MockOrdersService{ctrl: ctrl}
        mock.recorder = &MockOrdersServiceMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersService) EXPECT() *MockOrdersServiceMockRecorder {
        return m.recorder
}

// FindOrderByID mocks base method.
func (m *MockOrdersService) FindOrderByID(orderID string) (model.Order, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "FindOrderByID", orderID)
        ret0, _ := ret[0].(model.Order)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// FindOrderByID indicates an expected call of FindOrderByID.
func (mr *MockOrdersServiceMockRecorder) FindOrderByID(orderID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrderByID", reflect.TypeOf((*MockOrdersService)(nil).FindOrderByID), orderID)
}