// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/CarrenoG/go-workspace/src/examples/clean-architecture/3-hexagonal/bad-example/internal/core/ports/payments_service.go
//
// Generated by this command:
//
//      mockgen -source=C:/Users/CarrenoG/go-workspace/src/examples/clean-architecture/3-hexagonal/bad-example/internal/core/ports/payments_service.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
        context "context"
        reflect "reflect"

        model "github.com/gcarrenho/hexagonal/bad-example/internal/core/model"
        gomock "go.uber.org/mock/gomock"
)

// MockPaymentsService is a mock of PaymentsService interface.
type MockPaymentsService struct {
        ctrl     *gomock.Controller
        recorder *MockPaymentsServiceMockRecorder
        isgomock struct{}
}

// MockPaymentsServiceMockRecorder is the mock recorder for MockPaymentsService.
type MockPaymentsServiceMockRecorder struct {
        mock *MockPaymentsService
}

// NewMockPaymentsService creates a new mock instance.
func NewMockPaymentsService(ctrl *gomock.Controller) *MockPaymentsService {
        mock := &MockPaymentsService{ctrl: ctrl}
        mock.recorder = &MockPaymentsServiceMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentsService) EXPECT() *MockPaymentsServiceMockRecorder {
        return m.recorder
}

// FindPaymentByID mocks base method.
func (m *MockPaymentsService) FindPaymentByID(ctx context.Context, paymentID string) (model.Payment, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "FindPaymentByID", ctx, paymentID)
        ret0, _ := ret[0].(model.Payment)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// FindPaymentByID indicates an expected call of FindPaymentByID.
func (mr *MockPaymentsServiceMockRecorder) FindPaymentByID(ctx, paymentID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPaymentByID", reflect.TypeOf((*MockPaymentsService)(nil).FindPaymentByID), ctx, paymentID)
}

// OrderPaymentStatus mocks base method.
func (m *MockPaymentsService) OrderPaymentStatus(ctx context.Context, orderID string) (model.Payment, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "OrderPaymentStatus", ctx, orderID)
        ret0, _ := ret[0].(model.Payment)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// OrderPaymentStatus indicates an expected call of OrderPaymentStatus.
func (mr *MockPaymentsServiceMockRecorder) OrderPaymentStatus(ctx, orderID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderPaymentStatus", reflect.TypeOf((*MockPaymentsService)(nil).OrderPaymentStatus), ctx, orderID)
}